### PR TITLE
optimized gifs

### PR DESCRIPTION
**Pull request by adidalal**
Ran gifs through `gifsicle -O3` (http://davidwalsh.name/optimize-gifs)

### CODE REVIEW

**Comment by jpaik** [comment]
Hmm I see, I actually have gifs from the website that were optimized too. They are twice as small in size as the gifs that you are providing us. I will upload mine and see if there is a difference in quality!

**Comment by adityadalal924** [comment]
Depending on how you originally captured them, it may be better to recapture the .mp4 and use something like https://github.com/vvo/gifify for best optimization.

**Comment by jpaik** [comment]
Ahh I see! I believe I was just given the gif files. What I did was use gifsicle!
I used `gifsicle -O3 --lossy=(somewhere between 80-150) -o route-xx.gif route-xx.gif`

**Comment by adityadalal924** [comment]
Yep, didn't use lossy. That was the difference. Feel free to use those versions, in that case.

**Pull request closed without merging**
